---

hb_cli:
  - jq
  - xz
  - fd
  - bat
  - exa
  - mas
  - fzf
  - nnn
  - zip
  - unzip
  - tree
  - stow
  - htop
  - pwgen
  - neofetch
  - entr
  - renameutils
  - sc-im
  - figlet
  - rsync
  - itchyny/tap/mmv


hb_sys:
  - zsh
  - tmux
  - gpg


hb_devops:
  - awscli
  - ansible


hb_media:
  - ncmpcpp
  - mpd
  - mpc


hb_dev:
  - git
  - ctags
  - shellcheck
  - go
  - node
  - python
  - ccls
